steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ts-bridge:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ts-bridge:$BUILD_ID'
  - '.'

images:
- gcr.io/$PROJECT_ID/ts-bridge:$SHORT_SHA
- gcr.io/$PROJECT_ID/ts-bridge:$BUILD_ID