steps:

# Get the release tags from git
- name: gcr.io/cloud-builders/git
  args: [fetch, --depth=100, --tags]

- name: 'gcr.io/cloud-builders/git'
  id: 'Setup tags'
  entrypoint: '/bin/bash'
  args: ['-c', 'git describe --abbrev=0 --tags > _FULL_TAG']

- name: 'python'
  id: 'Generate tags'
  args: ['python3', 'git-version.py']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build image with custom tags'
  entrypoint: '/bin/bash'
  args:
  - '-ceux'
  - |
    docker build -t gcr.io/$PROJECT_ID/ts-bridge:git-$SHORT_SHA \
      -t gcr.io/$PROJECT_ID/ts-bridge:build-$BUILD_ID \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(date -u +%Y%m%dT%H%M) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _FULL_TAG) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _MAJOR_TAG) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _MINOR_TAG) \
      .

# TODO: Add major and minor tags
images:
- gcr.io/$PROJECT_ID/ts-bridge