---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-bridge-pv-claim
  namespace: ts-bridge
spec:
  storageClassName: ssd-backed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
