---
apiVersion: v1
kind: Service
metadata:
  name: ts-bridge-service
  namespace: ts-bridge
spec:
  type: ClusterIP
  selector:
    app: ts-bridge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
