steps:

- name: gcr.io/cloud-builders/git
  id: 'Fetch tags from git'
  args: [fetch, --depth=100, --tags]

- name: 'gcr.io/cloud-builders/git'
  id: 'Get version from git tags'
  entrypoint: '/bin/bash'
  args: ['-c', 'git describe --abbrev=0 --tags > _FULL_TAG']

- name: 'python:3'
  id: 'Create version tags'
  args: ['python3', 'ci/create-version-tags.py']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build image with custom tags'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker build -t gcr.io/$PROJECT_ID/ts-bridge:git-$SHORT_SHA \
      -t gcr.io/$PROJECT_ID/ts-bridge:build-$BUILD_ID \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(date -u +%Y%m%dT%H%M) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _FULL_TAG) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _MAJOR_TAG) \
      -t gcr.io/$PROJECT_ID/ts-bridge:$$(cat _MINOR_TAG) \
      .

# Push images to container registry
images:
- gcr.io/$PROJECT_ID/ts-bridge
