name: Tag and Release Go Binaries

on:
  push:
    branches:
      - master
    paths:
      - "version/ts-bridge-version.go"

jobs:
  tag-current-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up ts-bridge version
        run: echo "ts-bridge-version=$(grep -oP 'Ver = \"\K[^\"]+' version/ts-bridge-version.go)" >> $GITHUB_ENV

      - name: Create Release Tag with current commit
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.ts-bridge-version }}
          release_name: ${{ env.ts-bridge-version }}
          draft: false
          prerelease: false

  release-go-binaries:
    needs: tag-current-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set versions
        run: echo "go-version=$(cat .go-version)" >> $GITHUB_ENV

      - name: Set up Go according to .go-version
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Run GoReleaser according to .goreleaser.yml
        uses: goreleaser/goreleaser-action@v3
        with:
          workdir: app/
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
