name: Release Go Binaries

on:
  push:
    paths: ["version/.ts-bridge-version"]

jobs:
  release-go-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          custom_tag: $(cat version/.ts-bridge-version)
          github_token: ${{ secrets.TS_BRIDGE_BOT_TAG_TOKEN }}

      - name: Set Go version
        run: echo "go-version=$(cat .go-version)" >> $GITHUB_ENV

      - name: Set up Go according to .go-version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Run GoReleaser according to .goreleaser.yml
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: app/
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TS_BRIDGE_BOT_TAG_TOKEN }}
